from YahooFinanceAPI import YahooFinanceAPI as api

api.setDebugMode(True)
api.initializStockData("AMZN")
api.initializStockData("AAL")
api.getStockPriceAtClose("AMZN")
api.getStockPriceAfterHours("AMZN")
api.getPercentageChangeAtClose("AMZN")
api.getPointChangeAtClose("AMZN")
api.getPercentageChangeAfterHours("AMZN")
api.getPointChangeAfterHours("AMZN")
api.getPreviousClose('AMZN')
api.getOpen("AMZN")
api.getDayLow("AMZN")
api.getDayHigh("AMZN")
api.get52WeekLow("AMZN")
api.get52WeekHigh("AMZN")
api.getVolume("AMZN")
api.getAverageVolume("AMZN")
api.getMarketCap("AMZN")
api.getMarketCap("AAL")